name: fetch latest data and deploy to Adafruit IO

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # runs every 15 minutes

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install python dependencies
        run: pip install -r requirements.txt
      - name: run covidticker script to get the latest data
        run: python covidticker.py
